/**
 * NOTE: This class is auto generated by the swagger code generator program (2.4.7).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package com.ikano.lending.api;

import javax.validation.Valid;

import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.ikano.lending.model.Authenticate;
import com.ikano.lending.model.AuthenticateSuccess;

import io.swagger.annotations.Api;
import io.swagger.annotations.ApiOperation;
import io.swagger.annotations.ApiParam;
import io.swagger.annotations.ApiResponse;
import io.swagger.annotations.ApiResponses;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2019-08-12T08:01:00.768Z")

@Api(value = "authenticate", description = "the authenticate API")
public interface AuthenticateApi {

	@ApiOperation(value = "Autenticate User", nickname = "authenticateUser", notes = "", response = AuthenticateSuccess.class, tags = {
			"lending", })
	@ApiResponses(value = {
			@ApiResponse(code = 200, message = "User Authenticate Successfully", response = AuthenticateSuccess.class),
			@ApiResponse(code = 500, message = "Internal Server Error", response = Error.class) })
	@RequestMapping(value = "/authenticate", produces = { "application/json" }, consumes = {
			"application/json" }, method = RequestMethod.POST)
	ResponseEntity<AuthenticateSuccess> authenticateUser(
			@ApiParam(value = "Autenticate User", required = true) @Valid @RequestBody Authenticate authenticate);

}
